### ISSUE TITLE
token_bucket_refill tasks starts to grow in exponents

### ISSUE THREAD

**Issue by LennyLip** [RegioHelden/django-celery-token-bucket#11]
Thanks for the app! I have this conf and some time it work good 

```
CELERY_TOKEN_BUCKETS: Dict[str, TokenBucket] = {
    "api_client": TokenBucket(  # one per second
        name="api_client",
        schedule=timedelta(seconds=1),
        amount=1,
        maximum=1,
    )
}
```

But in some time pending tasks starts to grow in exponents. Any ideas?

Something like that: 

```
/data # redis-cli llen celery
(integer) 1743
/data # redis-cli LINDEX celery 0
"{\"body\": \"W1siYXV0b190cmFkZV9hcGlfY2xpZW50Il0sIHt9LCB7ImNhbGxiYWNrcyI6IG51bGwsICJlcnJiYWNrcyI6IG51bGwsICJjaGFpbiI6IG51bGwsICJjaG9yZCI6IG51bGx9XQ==\", \"content-encoding\": \"utf-8\", \"content-type\": \"application/json\", \"headers\": {\"lang\": \"py\", \"task\": \"django_celery_token_bucket.tasks.token_bucket_refill\", \"id\": \"1dff1f2f-89d4-44eb-9239-344686f96c39\", \"shadow\": null, \"eta\": null, \"expires\": null, \"group\": null, \"group_index\": null, \"retries\": 0, \"timelimit\": [null, null], \"root_id\": \"1dff1f2f-89d4-44eb-9239-344686f96c39\", \"parent_id\": null, \"argsrepr\": \"['api_client']\", \"kwargsrepr\": \"{}\", \"origin\": \"gen1@00b655a3bc97\", \"ignore_result\": false}, \"properties\": {\"correlation_id\": \"1dff1f2f-89d4-44eb-9239-344686f96c39\", \"reply_to\": \"9850bc41-8ce5-3835-9620-3c1b81cfb719\", \"periodic_task_name\": \"api_client\", \"delivery_mode\": 2, \"delivery_info\": {\"exchange\": \"\", \"routing_key\": \"celery\"}, \"priority\": 0, \"body_encoding\": \"base64\", \"delivery_tag\": \"397e49ee-f9f0-4a9a-abe7-c1a69f5f6319\"}}"
```

**Comment by lociii** [comment]
Thanks for the report. We've never tried running the refill every second. I can imagine that this will run into some race conditions.  
We're running the following schedule without any issues
```python
CELERY_TOKEN_BUCKETS: Dict[str, TokenBucket] = {
    "xxx": TokenBucket(
        name="xxx",
        schedule=schedules.crontab(minute=0),
        amount=3000,
        maximum=3000,
    )
}
```

![image](https://github.com/RegioHelden/django-celery-token-bucket/assets/366967/fb817ba8-e019-4ea5-9d2d-ca40cb5ed126)

Is the API that you're trying to throttle really giving one request per second?

**Comment by LennyLip** [comment]
I set the refill task (with the same config) to run once per 2 seconds.  Nothing changed, it works correctly 5-8 hours and then starts to grow in exponents

**Comment by LennyLip** [comment]
Ok, I'm ending up with separate queue for refill task and looks like it working ok now.
One moment will be nice, if we can use "exponential backoff" for countdown argument, or at least a jitter countdown.
Thank you for your work!

**Comment by LennyLip** [comment]
> race conditions.

Yes, you are right. Task execution time sometimes exceed 1 second, so second task starts before stop previous one. So, it's starts to grow in exponents.

Looks like, I need external script (management command may be) to refill queue.

**Comment by LennyLip** [comment]
<img width="537" alt="Screenshot 2023-10-02 at 21 16 18" src="https://github.com/RegioHelden/django-celery-token-bucket/assets/955994/b83905e6-2d1b-4855-9c16-f7bf758e98d4">

BTW, I need to purge queue before refill it. That's why I have a ton of messages, really. Any reason you didn't do it?

**Comment by lociii** [comment]
> BTW, I need to purge queue before refill it. That's why I have a ton of messages, really. Any reason you didn't do it?

This seems pretty weird. The kombu queue is set to only hold a certain maximum of messages.  
See https://github.com/RegioHelden/django-celery-token-bucket/blob/main/django_celery_token_bucket/bucket.py#L34

> Random countdown. Useful feature as for me.

I'd implement that a bit differently but could make sense sometimes.
